# Usar la imagen base de Python
FROM python:3.10

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar solo los archivos necesarios
COPY api.py ./

# Instalar dependencias sin requirements.txt
RUN pip install flask

# Crear un volumen para compartir el JSON
VOLUME /app/data

# Exponer el puerto para la API
EXPOSE 5002

# Ejecutar la API
CMD ["python", "api.py"]
